workflows:
  build-android:
    name: Build Android App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
